// ---------------- FRUIT TYPES ----------------
// Seasonal rotations — same location, fruit changes by season
const seasonalGroups = [
  { spring: "Ghost Berry",      summer: "Solberry",         fall: "Mirthshade",      winter: "Velvitfrost Berry" },
  { spring: "Azureberry",       summer: "Nightblush Berry", fall: "Mireberry",       winter: "Twilipuff" },
  { spring: "Skydrop Berry",    summer: "Tigermelon",       fall: "Mellowspike",     winter: "Faepeach" },
  { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip",       winter: "Frostgleam" },
  { spring: "Emberberry",       summer: "Heartgleam",       fall: "Seafallow Berry", winter: "Icerose Berry" },
  { spring: "Bloodberry",       summer: "Honeycran Berry",  fall: "Amberburst",      winter: "Lunabright" }
];

// Persistent fruits — present all year at these locations
// Azureberry and Ghost Berry have persistent locations separate from their seasonal ones
const fruitLocations = [
  // PERSISTENT:
  { id: 1, coords: [2349, 818],  type: "persistent", fruit: "Azureberry" },
  { id: 2, coords: [2239, 873],  type: "persistent", fruit: "Azureberry" },
  { id: 3, coords: [2302, 1251], type: "persistent", fruit: "Azureberry" },
  { id: 4, coords: [2166, 1118], type: "persistent", fruit: "Azureberry" },
  { id: 5, coords: [2626, 2456], type: "persistent", fruit: "Ghost Berry" },
  { id: 6, coords: [2697, 2376], type: "persistent", fruit: "Ghost Berry" },
  { id: 7, coords: [2585, 2356], type: "persistent", fruit: "Ghost Berry" },

  // SEASONAL:
  { id: 8,  coords: [2942, 2344], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 9,  coords: [2986, 2274], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 10, coords: [2965, 2250], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 11, coords: [2842, 2287], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 12, coords: [2851, 2507], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 13, coords: [2624, 2184], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 14,  coords: [2716, 2024], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 15,  coords: [2703, 1895], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 16, coords: [2879, 1366], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 17, coords: [3059, 2259], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 18, coords: [3093, 2281], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 19, coords: [3070, 2214], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 20,  coords: [3114, 2251], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 21,  coords: [1930, 2621], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },
  { id: 22, coords: [1883, 2607], type: "seasonal", fruits: { spring: "Ghost Berry", summer: "Solberry", fall: "Mirthshade", winter: "Velvitfrost Berry" } },

  { id: 23,  coords: [3011, 2527], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 24,  coords: [3056, 2546], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 25,  coords: [2834, 2063], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 26,  coords: [2420, 2580], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 27,  coords: [2478, 2576], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 28,  coords: [2607, 3700], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 29,  coords: [2662, 3482], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 30,  coords: [2551, 3372], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 31,  coords: [2730, 1680], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 32,  coords: [2746, 1562], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 33,  coords: [2702, 1472], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 34,  coords: [2646, 864], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 35,  coords: [2732, 1019], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 36,  coords: [2765, 1101], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 37,  coords: [1960, 1940], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 38,  coords: [1936, 2032], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 39,  coords: [1897, 2048], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 40,  coords: [1849, 2041], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },
  { id: 41,  coords: [1821, 2917], type: "seasonal", fruits: { spring: "Azureberry", summer: "Nightblush Berry", fall: "Mireberry", winter: "Twilipuff" } },

  { id: 42,  coords: [3064, 2584], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 43,  coords: [3043, 2644], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 44,  coords: [3145, 2632], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 45,  coords: [3102, 2696], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 46,  coords: [3130, 2787], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 47,  coords: [3103, 2824], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 48,  coords: [3000, 2915], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 49,  coords: [2814, 2868], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 50,  coords: [2843, 2692], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 51,  coords: [2297, 1615], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 52,  coords: [2225, 1432], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 53,  coords: [2181, 1510], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 54,  coords: [2215, 1696], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 55,  coords: [2179, 1740], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 56,  coords: [2069, 1753], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 57,  coords: [2138, 1595], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },
  { id: 58,  coords: [2184, 1842], type: "seasonal", fruits: { spring: "Skydrop Berry", summer: "Tigermelon", fall: "Mellowspike", winter: "Faepeach" } },

  { id: 59,  coords: [2863, 1952], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 60,  coords: [2996, 2083], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 61,  coords: [2968, 2055], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 62,  coords: [2802, 1882], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 63,  coords: [2799, 1833], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 64,  coords: [2877, 1581], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 65,  coords: [3292, 2576], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 66,  coords: [3241, 2764], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 67,  coords: [3246, 2783], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 68,  coords: [2196, 3491], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 69,  coords: [2237, 3651], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 70,  coords: [1822, 2016], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 71,  coords: [1897, 1888], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },
  { id: 72,  coords: [1835, 1910], type: "seasonal", fruits: { spring: "Nightshade Berry", summer: "Velvenight Berry", fall: "Scarletip", winter: "Frostgleam" } },

  { id: 73,  coords: [1782, 2609], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 74,  coords: [1691, 2694], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 75,  coords: [1754, 2778], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 76,  coords: [1781, 2950], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 77,  coords: [1494, 3107], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 78,  coords: [1446, 3122], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 79,  coords: [1455, 3077], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 80,  coords: [1311, 3036], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 81,  coords: [1187, 3076], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 82,  coords: [1318, 2926], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 83,  coords: [1368, 2874], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 84,  coords: [1375, 2702], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 85,  coords: [1438, 2600], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 86,  coords: [1573, 2577], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 87,  coords: [1629, 2554], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },
  { id: 88,  coords: [1677, 2563], type: "seasonal", fruits: { spring: "Emberberry", summer: "Heartgleam", fall: "Seafallow Berry", winter: "Icerose Berry" } },

  { id: 89,  coords: [2561, 3281], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 90,  coords: [1622, 2178], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 91,  coords: [1556, 2421], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 92,  coords: [1534, 2480], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 93,  coords: [1461, 2535], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 94,  coords: [1367, 2567], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 95,  coords: [1277, 2593], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 96,  coords: [1264, 2615], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 97,  coords: [1321, 2688], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 98,  coords: [1332, 2747], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 99,  coords: [1310, 2768], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 100,  coords: [1228, 2773], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 101,  coords: [1207, 2802], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  { id: 102,  coords: [1528, 2877], type: "seasonal", fruits: { spring: "Bloodberry", summer: "Honeycran Berry", fall: "Amberburst", winter: "Lunabright" } },
  
  // APPLES:
  { id: 103, coords: [2969, 2365], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 104, coords: [3138, 2168], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 105, coords: [3136, 2131], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 106, coords: [3129, 2098], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 107, coords: [3170, 2167], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 108, coords: [3167, 2128], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 109, coords: [3159, 2095], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 110, coords: [3203, 2164], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 111, coords: [3199, 2125], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 112, coords: [3192, 2089], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 113, coords: [3235, 2158], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 114, coords: [3229, 2121], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 115, coords: [3224, 2087], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 116, coords: [3264, 2116], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } },
  { id: 117, coords: [3257, 2082], type: "seasonal", fruits: { spring: "Greenwhistle Apple", summer: "Sunapple", fall: "Amberfall Apple", winter: "Frostveil Apple" } }
];

